---
# this is a place-holder workflow in order to align action workflow to the overall CI process

name: re-build-test

on:  # yamllint disable-line rule:truthy

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
